### ISSUE TITLE
Problem with compose

### ISSUE THREAD

**Issue by galbirk** [luminousmen/semarchy-docker#1]
hey, 

I have tried your code, ad I'm getting this error while trying access semarchy...
**url:** http://ip:8080/semarchy

![image](https://user-images.githubusercontent.com/62448908/95004726-ea3f2580-05f7-11eb-859b-67d059dd5b86.png)

**Comment by mdahlman** [comment]
I realize that this is an old issue. But for future users, here's a little insight.

That error is a "good error" in the sense that it's expected the first time you attempt to run Semarchy xDM. It indicates that you successfully connected to the database schema containing the repository tables, but it failed to find any tables. The next thing xDM will do is create those tables (starting with mta_repository).

**Comment by galbirk** [comment]
Hey, 

This is indeed an old issue and I succeed to solve it.
The thing was that I couldn't connect to semarchy url...
